"""Allure reporting helpers: checks, templates, instrumentation."""

from partest.reporting.checks import (
    check_between,
    check_eq,
    check_false,
    check_in,
    check_in_list,
    check_is_none,
    check_isinstance,
    check_len,
    check_lt,
    check_ne,
    check_not_empty,
    check_not_in,
    check_not_startswith,
    check_status,
    check_status_in,
    check_true,
)
from partest.reporting.instrument import (
    build_http_step_title,
    instrumented_make_request,
)
from partest.reporting.templates import (
    DescriptionTemplates,
    ErrorTemplates,
    Severity,
    StepTemplates,
    format_http_status_failure,
    http_status_hint,
    set_conflict_hint_provider,
    set_status_hints_locale,
    status_hints_locale,
)
from partest.reporting.attach import (
    attach_check,
    attach_failure,
    attach_json,
    attach_request,
    attach_response,
    attach_text,
)
from partest.reporting.steps import step, step_as_role, step_cleanup, step_http, step_prepare
from partest.reporting.testcase import set_description, set_title, testcase

__all__ = [
    "Severity",
    "ErrorTemplates",
    "StepTemplates",
    "DescriptionTemplates",
    "http_status_hint",
    "format_http_status_failure",
    "set_conflict_hint_provider",
    "set_status_hints_locale",
    "status_hints_locale",
    "attach_json",
    "attach_text",
    "attach_request",
    "attach_response",
    "attach_check",
    "attach_failure",
    "step",
    "step_http",
    "step_prepare",
    "step_cleanup",
    "step_as_role",
    "check_eq",
    "check_ne",
    "check_true",
    "check_false",
    "check_in_list",
    "check_isinstance",
    "check_status",
    "check_status_in",
    "check_in",
    "check_not_in",
    "check_len",
    "check_not_empty",
    "check_is_none",
    "check_not_startswith",
    "check_between",
    "check_lt",
    "testcase",
    "set_description",
    "set_title",
    "build_http_step_title",
    "instrumented_make_request",
]
