"""Recursively generate package ``__init__.py`` re-exports (project-agnostic).

Usage::

    python -m partest.tools.generate_init --directory src/api/resources
    partest-gen init-package-exports src/api/resources
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional, Sequence, Set


DEFAULT_EXCLUDE_FILES = frozenset(
    {"__init__.py", "tests.py", "utils.py", "generate_init.py", "conftest.py"}
)
DEFAULT_EXCLUDE_DIRS = frozenset({"__pycache__", "tests", "docs", ".git", ".venv", "venv"})


def generate_init_for_directory(
    directory: Path,
    output_file: str = "__init__.py",
    *,
    exclude_files: Optional[Set[str]] = None,
    exclude_dirs: Optional[Set[str]] = None,
    banner: str = "# AUTO-GENERATED by partest.tools.generate_init — safe to re-run\n",
    recursive: bool = True,
) -> list[Path]:
    """Write ``__init__.py`` with ``from .mod import *`` for packages.

    Returns list of written paths.
    """
    directory = Path(directory).resolve()
    if not directory.is_dir():
        raise FileNotFoundError(f"directory not found: {directory}")

    exclude_files = set(exclude_files or DEFAULT_EXCLUDE_FILES)
    exclude_dirs = set(exclude_dirs or DEFAULT_EXCLUDE_DIRS)
    written: list[Path] = []

    imports: list[str] = []
    for item in sorted(directory.iterdir(), key=lambda p: p.name.lower()):
        if item.is_file() and item.suffix == ".py" and item.name not in exclude_files:
            imports.append(f"from .{item.stem} import *")
        elif (
            item.is_dir()
            and item.name not in exclude_dirs
            and (item / "__init__.py").exists()
        ):
            imports.append(f"from .{item.name} import *")

    if imports:
        init_path = directory / output_file
        body = banner + "\n".join(imports) + "\n"
        init_path.write_text(body, encoding="utf-8")
        written.append(init_path)

    if recursive:
        for item in directory.iterdir():
            if item.is_dir() and item.name not in exclude_dirs:
                written.extend(
                    generate_init_for_directory(
                        item,
                        output_file,
                        exclude_files=exclude_files,
                        exclude_dirs=exclude_dirs,
                        banner=banner,
                        recursive=True,
                    )
                )
    return written


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m partest.tools.generate_init",
        description="Generate package __init__.py re-exports recursively.",
    )
    parser.add_argument(
        "--directory",
        "-d",
        required=True,
        help="Root directory to scan (e.g. src/api/resources)",
    )
    parser.add_argument(
        "--output-file",
        default="__init__.py",
        help="Init file name (default __init__.py)",
    )
    parser.add_argument(
        "--no-recursive",
        action="store_true",
        help="Only write init in the top directory",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(list(argv) if argv is not None else None)

    try:
        written = generate_init_for_directory(
            Path(args.directory),
            args.output_file,
            recursive=not args.no_recursive,
        )
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    if args.verbose or not written:
        print(f"Wrote {len(written)} file(s) under {Path(args.directory).resolve()}")
        for p in written:
            print(f"  + {p}")
    else:
        print(f"Wrote {len(written)} __init__.py file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
